---
- name: Cluster prep
  hosts: cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s_prereq

- name: Setup K3S server
  hosts: k3s_master_host
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: 
    - k3s_worker_host_1
    - k3s_worker_host_2
  become: true
  roles:
    - role: k3s_agent
