---
- name: Deploy Promtail service
  ansible.builtin.include_tasks:
    file: "deploy.yml"
  when: not promtail_uninstall

- name: Modify Docker logopt
  ansible.builtin.include_tasks:
    file: "change_logopt.yml"
  when: 
    - modify_docker_logopt
    - __docker_installed

- name: Uninstall Promtail service
  ansible.builtin.include_tasks:
    file: "uninstall.yml"
  when: promtail_uninstall