---
- name: Deploy Loki service
  ansible.builtin.include_tasks:
    file: "deploy.yml"
  when: not loki_uninstall

- name: Uninstall Loki service
  ansible.builtin.include_tasks:
    file: "uninstall.yml"
  when: loki_uninstall
