---
- name: Check already exists key for {{ ansible_host }}
  ansible.builtin.shell: "cat /home/{{ ansible_user }}/.ssh/authorized_keys"
  register: existing_keys

- name: Adding key user {{ item }} in {{ ansible_host }}
  ansible.builtin.shell: "echo '{{ ssh_key[item] }}' >> /home/{{ ansible_user }}/.ssh/authorized_keys"
  when: not ssh_key[item] in existing_keys.stdout
