- name: Install icinga2-ido-mysql package
  ansible.builtin.apt:
    name: icinga2-ido-mysql
    state: present

- name: Enable ido-mysql feature for Icinga2
  ansible.builtin.command:
    cmd: icinga2 feature enable ido-mysql

- name: Configure ido-mysql with dbconfig
  ansible.builtin.command:
    cmd: icinga2 ido-mysql config
  register: dbconfig_output
  become: true

- name: Set MySQL password for icinga2 user for all hosts
  ansible.builtin.mysql_user:
    name: icinga2
    password: "{{ icinga_db_password }}"
    state: present
    host: "%"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Set MySQL password for icinga2 user for localhost
  ansible.builtin.mysql_user:
    name: icinga2
    password: "{{ icinga_db_password }}"
    state: present
    host: "localhost"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Change authentication method for root MySQL user
  ansible.builtin.mysql_query:
    query: "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ icinga_db_password }}';"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
  register: query_result

- name: Change authentication method for icinga2 MySQL user for all hosts
  ansible.builtin.mysql_query:
    query: "ALTER USER 'icinga2'@'%' IDENTIFIED WITH mysql_native_password BY '{{ icinga_db_password }}';"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
  register: query_result

- name: Change authentication method for icinga2 MySQL user for localhost
  ansible.builtin.mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    query: "ALTER USER 'icinga2'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ icinga_db_password }}';"
  register: query_result

- name: Enable ido-mysql feature for Icinga2
  ansible.builtin.command:
    cmd: icinga2 feature enable ido-mysql

- name: Replace ido-mysql.conf with updated configuration
  ansible.builtin.template:
    src: ido-mysql.conf.j2
    dest: /etc/icinga2/features-enabled/ido-mysql.conf
  become: true

- name: List all enabled Icinga2 features
  ansible.builtin.command:
    cmd: icinga2 feature list
  register: icinga2_features

- name: Restart Icinga2 service
  ansible.builtin.systemd:
    name: icinga2
    state: restarted
